/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// DaprInstanceSpecApplyConfiguration represents a declarative configuration of the DaprInstanceSpec type for use
// with apply.
type DaprInstanceSpecApplyConfiguration struct {
	Deployment *DeploymentSpecApplyConfiguration `json:"deployment,omitempty"`
	Chart      *ChartSpecApplyConfiguration      `json:"chart,omitempty"`
	Values     *JSONApplyConfiguration           `json:"values,omitempty"`
}

// DaprInstanceSpecApplyConfiguration constructs a declarative configuration of the DaprInstanceSpec type for use with
// apply.
func DaprInstanceSpec() *DaprInstanceSpecApplyConfiguration {
	return &DaprInstanceSpecApplyConfiguration{}
}

// WithDeployment sets the Deployment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deployment field is set to the value of the last call.
func (b *DaprInstanceSpecApplyConfiguration) WithDeployment(value *DeploymentSpecApplyConfiguration) *DaprInstanceSpecApplyConfiguration {
	b.Deployment = value
	return b
}

// WithChart sets the Chart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Chart field is set to the value of the last call.
func (b *DaprInstanceSpecApplyConfiguration) WithChart(value *ChartSpecApplyConfiguration) *DaprInstanceSpecApplyConfiguration {
	b.Chart = value
	return b
}

// WithValues sets the Values field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Values field is set to the value of the last call.
func (b *DaprInstanceSpecApplyConfiguration) WithValues(value *JSONApplyConfiguration) *DaprInstanceSpecApplyConfiguration {
	b.Values = value
	return b
}
