version: "2"
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - godox
    - ireturn
    - mnd
    - paralleltest
    - varnamelen
    - funcorder
    - staticcheck
    - recvcheck
    - noinlineerr
    - wsl
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      disable:
    funlen:
      ignore-comments: true
    lll:
      line-length: 170
    mnd:
      checks:
        - argument
        - case
        - operation
        - return
        - assign
      ignored-functions:
        - ^len\.
        - ^strings\.SplitN$
        - ^make$
    nlreturn:
      block-size: 2
    revive:
      rules:
        - name: dot-imports
          disabled: true
    testpackage:
      skip-regexp: test/e2e/...
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoinits
          - wrapcheck
        path: test
      - linters:
          - gochecknoinits
        path: api
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
