/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/dapr/kubernetes-operator/api/operator/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// DaprCruiseControlLister helps list DaprCruiseControls.
// All objects returned here must be treated as read-only.
type DaprCruiseControlLister interface {
	// List lists all DaprCruiseControls in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.DaprCruiseControl, err error)
	// Get retrieves the DaprCruiseControl from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.DaprCruiseControl, error)
	DaprCruiseControlListerExpansion
}

// daprCruiseControlLister implements the DaprCruiseControlLister interface.
type daprCruiseControlLister struct {
	listers.ResourceIndexer[*v1beta1.DaprCruiseControl]
}

// NewDaprCruiseControlLister returns a new DaprCruiseControlLister.
func NewDaprCruiseControlLister(indexer cache.Indexer) DaprCruiseControlLister {
	return &daprCruiseControlLister{listers.New[*v1beta1.DaprCruiseControl](indexer, v1beta1.Resource("daprcruisecontrol"))}
}
