/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DaprChartSpecApplyConfiguration represents an declarative configuration of the DaprChartSpec type for use
// with apply.
type DaprChartSpecApplyConfiguration struct {
	Repo    *string `json:"repo,omitempty"`
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

// DaprChartSpecApplyConfiguration constructs an declarative configuration of the DaprChartSpec type for use with
// apply.
func DaprChartSpec() *DaprChartSpecApplyConfiguration {
	return &DaprChartSpecApplyConfiguration{}
}

// WithRepo sets the Repo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repo field is set to the value of the last call.
func (b *DaprChartSpecApplyConfiguration) WithRepo(value string) *DaprChartSpecApplyConfiguration {
	b.Repo = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DaprChartSpecApplyConfiguration) WithName(value string) *DaprChartSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *DaprChartSpecApplyConfiguration) WithVersion(value string) *DaprChartSpecApplyConfiguration {
	b.Version = &value
	return b
}
